apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: argocd-test-app-0
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30036
  selector:
    app: mysql