apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-erik-kubica-dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-erik-kubica-dev
  template:
    metadata:
      labels:
        app: web-erik-kubica-dev
    spec:
      containers:
        - name: web-erik-kubica-dev
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: FORCE_SSL_ADMIN
              value: "true"
            - name: FORCE_SSL_LOGIN
              value: "true"  
          volumeMounts:
            - name: volume
              mountPath: /var/www/html
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: web-erik-kubica-dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-erik-kubica-dev 
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/erik-kubica.dev/public_html
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - erik-kubica-xps-15-7590
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-erik-kubica-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: web-erik-kubica-dev
---
apiVersion: v1
kind: Service
metadata:
  name: web-erik-kubica-dev
spec:
  selector:
    app: web-erik-kubica-dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-erik-kubica-dev
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
    - host: erik-kubica.dev
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-erik-kubica-dev
                port:
                  number: 80
  tls:
    - hosts:
      - erik-kubica.dev
      - www.erik-kubica.dev
      secretName: erik-kubica-dev-tls